### user create
POST http://localhost:5000/api/v1/users
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

### users get
GET http://localhost:5000/api/v1/users  

### user edit
PUT http://localhost:5000/api/v1/users
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "test",
    "newPassword": "hello"
}

### user delete
DELETE http://localhost:5000/api/v1/users
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

### user login
POST http://localhost:5000/api/v1/login
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "test@gmail.com"
}